spring:

  profiles: dev

  thymeleaf:
    # do not cache -> hot reload of templates
    cache: false

#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/grottodb
#    username: santa
#    password: ${db_password}
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      connection:
        charset: utf8
        useUnicode: true
        # Hibernate ddl auto (create, create-drop, update): with "update" the database
        # schema will be automatically updated accordingly to java entities found in
        # the project
      ddl-auto: update
      # Show or not log for each sql query
#      show-sql: false
    # Naming strategy
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# Allows Hibernate to generate SQL optimized for a particular DBMS
#    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

