initial_admin_account:
  username: admin
  password: ${initial_admin_password}


logging:
  level:
    root: INFO
    ac.uk.bristol.cs.santa.grotto: DEBUG
    org.springframework.web: DEBUG
  file:
    path: logs

spring:
  #  set env variable SPRING_PROFILES_ACTIVE=dev on dev machine
  profiles.active: prod

  thymeleaf:
    cache: false


  application:
    name: demoservice
#server:
#  port: 9090