apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: postgres-config
  env: PG_CONFIG.txt

secretGenerator:
- name: mysecret
  env: PG_CONFIG.txt