apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spe-demo
spec:
  type: NodePort
  ports:
    # outside
  - port: 8080
    name: http
  selector:
    app: spe-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-depl
  labels:
    app: spe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spe-demo
  template:
    metadata:
      labels:
        app: spe-demo
    spec:
      containers:
      - name: spe-demo
        image: dschien/spe-simple-demo
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
          # inside container
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: dbhost
          value: "postgres"
          # https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_PASSWORD
#        envFrom:
#        - secretRef:
#            name: mysecret

